apiVersion: v1
kind: Pod
metadata:
  name: jw
spec:
  initContainers:
  - image: resouer/sample:v2
    name: war
    command: ["cp", "/hello.war","/app"]
    volumeMounts:
    - mountPath: /app
      name: app-volume
  containers:
  - image: tomcat:7.0
    name: tomcat
    volumeMounts:
    - mountPath: /usr/local/tomcat/webapps
      name: app-volume
    ports:
    - containerPort: 8080
      hostPort: 8001
  nodeSelector:
    zone: south
  volumes:
  - name: app-volume
    emptyDir: {}
