#!/bin/bash

if [ $1 == help ]; then
 echo 'Options:  kubectl get pods -o wide   # show pods in which nodes.'
 echo 'get [pod | rc | hpa | jobs | nodes] '
 echo 'kubectl get pods --namespace=kube-system'
 exit
fi 

echo -e "$T \033[1;32m kubectl get $1 $2 $3"
kubectl get $1 $2 $3
