apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master-vlatest
  labels:
    name: redis-master
    version: vlatest
spec:
  replicas: 3
  selector:
    name: redis-master
    version: vlatest
  template:
    metadata:
      labels:
        name: redis-master
        version: vlatest
    spec:
      containers:
      - name: master
        image: kubeguide/redis-master:latest
        ports:
        - containerPort: 6379
      nodeSelector:     # 定向调度
        zone: north
