apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-rbd-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.10.8.61:6789 
    pool: rbd
    image: test
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
