apiVersion: v1
kind: Pod
metadata:
  name: ceph-pod1
spec:
  nodeName: node-8-61
  containers:
  - name: nginx
    image: nginx:1.14
    volumeMounts:
    - name: ceph-pvc 
      mountPath: /usr/share/nginx/html
      readOnly: false
  volumes:
  - name: ceph-pvc
    persistentVolumeClaim:
      claimName: ceph-pvc
