#!/bin/bash
# count files in the dict
touch countlist
>countlist

IFS=":"
count=0; nonex=0
for directory in $PATH ; do
	if [ -d "$directory" ] ; then
		for command in "$directory"/* ; do
			if [ -x "$command" ] ; then
				#echo $command | awk -F"\/" {'print $3'} >> countlist
				echo $command >> countlist
				count="$(( $count + 1 ))"
			else
				nonex="$(( $nonex + 1 ))"
			fi
		done
	fi
done

echo "$count commands , and $nonex entries that were not executalbe"

exit 0

