apiVersion: v1
kind: Service
metadata:
  labels:
    name: cassandra
  name: cassandra
spec:
  ports:
  - port: 9042   
  #clusterIP: None   #Headless Service do not set CIP.
  selector:
    name: cassandra
