#!/bin/bash

if [[ $2 == 'kube' ]]; then
  echo -e "$T \033[1;32m kubectl log $1 --namespace=kube-system"
  kubectl log $1 --namespace=kube-system
  exit
fi

echo -e "$T \033[1;32m kubectl log -f $1 $2" 
kubectl logs -f $1 $2 
