#!/bin/bash
if [[ $3 == 'ks' ]]; then
  echo -e "$T \033[1;32m kubectl delete $1 $2  --namespace=kube-system"
  kubectl delete $1 $2  --namespace=kube-system
  exit
fi

if [[ $3 == 'name' ]]; then
  echo -e "$T \033[1;32m kubectl delete $1 $2 --namespace=$4"
  kubectl delete $1 $2 --namespace=$4
  exit
fi


echo -e "$T \033[1;32m kubectl delete $1 $2" 
if [ ! -n "$2" ]; then  
	echo "Need pods name" 
else
	kubectl delete $1 $2
	kubectl get $1 -o wide
fi 
