apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
spec:
  containers:
  - name: kubenetes-serve-hostname
    image: anjia0532/serve_hostname
    resources:
      limits:
        cpu: "5"
        memory: 100Mi
